#![cfg(feature = "test-servers")]

use std::sync::Arc;

use axum::Router;
use axum::body::{Body, Bytes};
use axum::http::{HeaderMap, StatusCode, header};
use axum::response::Response;
use axum::routing::post;

use grpctestify::assert::engine::{AssertionEngine, AssertionResult};
use grpctestify::grpc::client::{CompressionMode, GrpcClientConfig, ProtoConfig, WireProtocol};
use grpctestify::grpc::web::execute_web;
use grpctestify::plugins::PluginManager;

use prost::Message;
use serde_json::{Value, json};
use tempfile::NamedTempFile;

mod echo_proto {
    tonic::include_proto!("echo");
}
use echo_proto::{HelloRequest, HelloResponse, StreamRequest, StreamResponse};

// FileDescriptorSet for the reference services, generated by build.rs under the
// `test-servers` feature. The Connect binary/streaming paths need a descriptor to
// resolve the RPC mode and marshal JSON <-> protobuf.
const TEST_SERVERS_DESCRIPTOR: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/test_servers_descriptor.bin"));

// Base64 of `{"reason":"BOOM"}` — a recognizable detail value so tests can assert
// the Connect error `details` array round-trips through the transport verbatim.
const DETAIL_VALUE_B64: &str = "eyJyZWFzb24iOiJCT09NIn0=";

/// Encode one Connect envelope frame: 1 flag byte + 4-byte big-endian length +
/// payload. `flag` is `0x00` for a data frame, `0x02` for the end-of-stream frame.
fn encode_envelope(flag: u8, data: &[u8]) -> Vec<u8> {
    let mut buf = Vec::with_capacity(5 + data.len());
    buf.push(flag);
    buf.extend_from_slice(&(data.len() as u32).to_be_bytes());
    buf.extend_from_slice(data);
    buf
}

/// Read the first Connect envelope from a request body, returning its payload.
/// The transport marks the request frame end-of-stream, but the server only needs
/// the payload, so the flag is ignored.
fn decode_first_envelope(data: &[u8]) -> Option<&[u8]> {
    if data.len() < 5 {
        return None;
    }
    let len = u32::from_be_bytes([data[1], data[2], data[3], data[4]]) as usize;
    data.get(5..5 + len)
}

fn wants_proto(headers: &HeaderMap) -> bool {
    headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .is_some_and(|c| c.contains("proto"))
}

/// A Connect unary error: non-2xx HTTP status + `{"code","message","details"?}`
/// JSON body. This is exactly what `connect_error_from_json` in src/grpc/web.rs
/// decodes into a structured `GrpcError`.
fn connect_error(status: StatusCode, body: Value) -> Response {
    Response::builder()
        .status(status)
        .header(header::CONTENT_TYPE, "application/json")
        .body(Body::from(serde_json::to_vec(&body).unwrap()))
        .unwrap()
}

/// Connect unary handler for `echo.EchoService/SayHello`. Speaks JSON
/// (`application/json`) and binary (`application/proto`); the request body is the
/// bare message (no envelope). Branches on the message so tests can drive success,
/// an error, and an error carrying `details`.
async fn say_hello(headers: HeaderMap, body: Bytes) -> Response {
    let is_proto = wants_proto(&headers);
    let message = if is_proto {
        HelloRequest::decode(&body[..])
            .map(|r| r.message)
            .unwrap_or_default()
    } else {
        serde_json::from_slice::<Value>(&body)
            .ok()
            .and_then(|v| {
                v.get("message")
                    .and_then(|m| m.as_str())
                    .map(str::to_string)
            })
            .unwrap_or_default()
    };

    if message == "boom" {
        return connect_error(
            StatusCode::NOT_FOUND,
            json!({ "code": "not_found", "message": "greeting not found" }),
        );
    }
    if message == "boom-details" {
        return connect_error(
            StatusCode::BAD_REQUEST,
            json!({
                "code": "invalid_argument",
                "message": "bad greeting",
                "details": [{ "type": "google.rpc.ErrorInfo", "value": DETAIL_VALUE_B64 }],
            }),
        );
    }

    let reply = format!("Hello, {}!", message);
    let (content_type, out) = if is_proto {
        (
            "application/proto",
            HelloResponse { message: reply }.encode_to_vec(),
        )
    } else {
        (
            "application/json",
            serde_json::to_vec(&json!({ "message": reply })).unwrap(),
        )
    };

    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, content_type)
        // Leading metadata surfaces as an HTTP response header over Connect.
        .header("x-custom-header", "custom-value")
        .body(Body::from(out))
        .unwrap()
}

/// Connect server-streaming handler for `echo.EchoService/ServerStream`. Reads the
/// single enveloped request message, emits `count` enveloped data frames, then a
/// terminal EndStreamMessage envelope (flag `0x02`) with `metadata` (surfaced as
/// trailers) and — when `prefix == "err"` — an `error`.
async fn server_stream(headers: HeaderMap, body: Bytes) -> Response {
    let is_proto = wants_proto(&headers);
    let payload = decode_first_envelope(&body).unwrap_or(&[]);
    let req = if is_proto {
        StreamRequest::decode(payload).unwrap_or_default()
    } else {
        let v: Value = serde_json::from_slice(payload).unwrap_or_else(|_| json!({}));
        StreamRequest {
            prefix: v
                .get("prefix")
                .and_then(|p| p.as_str())
                .unwrap_or_default()
                .to_string(),
            count: v.get("count").and_then(|c| c.as_i64()).unwrap_or(0) as i32,
        }
    };

    let err_mode = req.prefix == "err";
    // In the error case still stream a couple of data frames before the failing
    // end-of-stream frame, so tests see both messages AND the terminal error.
    let count = if err_mode { 2 } else { req.count };

    let mut out = Vec::new();
    for i in 0..count {
        let resp = StreamResponse {
            index: i,
            message: format!("{} #{}", req.prefix, i),
        };
        let data = if is_proto {
            resp.encode_to_vec()
        } else {
            serde_json::to_vec(&json!({ "index": resp.index, "message": resp.message })).unwrap()
        };
        out.extend_from_slice(&encode_envelope(0x00, &data));
    }

    // Connect EndStreamMessage is ALWAYS JSON, even for `+proto` streams.
    let end = if err_mode {
        json!({
            "error": {
                "code": "resource_exhausted",
                "message": "stream blew up",
                "details": [{ "type": "google.rpc.RetryInfo", "value": DETAIL_VALUE_B64 }],
            },
            "metadata": { "x-stream-trailer": ["trailer-value"] },
        })
    } else {
        json!({ "metadata": { "x-stream-trailer": ["trailer-value"] } })
    };
    out.extend_from_slice(&encode_envelope(0x02, &serde_json::to_vec(&end).unwrap()));

    let content_type = if is_proto {
        "application/connect+proto"
    } else {
        "application/connect+json"
    };
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, content_type)
        .header("x-custom-header", "custom-value")
        .body(Body::from(out))
        .unwrap()
}

/// Spawn the minimal Connect server on an ephemeral port, returning its
/// `http://host:port` base address. Built on axum/hyper (already workspace deps);
/// the Connect framing is hand-serialized in the handlers above.
async fn spawn_connect_server() -> String {
    let app = Router::new()
        .route("/echo.EchoService/SayHello", post(say_hello))
        .route("/echo.EchoService/ServerStream", post(server_stream));

    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .expect("bind ephemeral port");
    let addr = listener.local_addr().expect("local addr");

    tokio::spawn(async move {
        axum::serve(listener, app).await.expect("server run");
    });

    format!("http://{}", addr)
}

/// Descriptor file kept alive for the duration of a test (drop = delete).
fn descriptor_file() -> NamedTempFile {
    let file = NamedTempFile::new().expect("temp descriptor");
    std::fs::write(file.path(), TEST_SERVERS_DESCRIPTOR).expect("write descriptor");
    file
}

/// Build a Connect client config. Passing a descriptor path routes unary calls
/// through the binary (`application/proto`) path and lets the transport resolve
/// the streaming RPC mode; `None` keeps unary on the JSON path.
fn connect_config(address: &str, descriptor: Option<&str>) -> GrpcClientConfig {
    GrpcClientConfig {
        address: address.to_string(),
        timeout_seconds: 5,
        tls_config: None,
        proto_config: descriptor.map(|d| ProtoConfig {
            files: vec![],
            import_paths: vec![],
            descriptor: Some(d.to_string()),
        }),
        metadata: None,
        target_service: None,
        compression: CompressionMode::None,
        connection_id: 0,
        protocol: WireProtocol::ConnectRpc,
        version: "test".to_string(),
    }
}

fn engine() -> AssertionEngine {
    AssertionEngine::with_registry(Arc::new(PluginManager::new()))
}

#[tokio::test]
async fn connect_unary_json_success() {
    let address = spawn_connect_server().await;
    let config = connect_config(&address, None);

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "World" }),
    )
    .await
    .expect("connect unary json call");

    assert!(resp.error.is_none(), "unexpected error: {:?}", resp.error);
    assert_eq!(resp.messages.len(), 1, "messages: {:?}", resp.messages);
    assert_eq!(resp.messages[0]["message"], json!("Hello, World!"));
}

#[tokio::test]
async fn connect_unary_proto_success() {
    // A descriptor routes the call through `application/proto`: proto request
    // bytes, proto response bytes decoded via the output descriptor.
    let address = spawn_connect_server().await;
    let desc = descriptor_file();
    let config = connect_config(&address, Some(&desc.path().to_string_lossy()));

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "Proto" }),
    )
    .await
    .expect("connect unary proto call");

    assert!(resp.error.is_none(), "unexpected error: {:?}", resp.error);
    assert_eq!(resp.messages.len(), 1, "messages: {:?}", resp.messages);
    assert_eq!(resp.messages[0]["message"], json!("Hello, Proto!"));
}

#[tokio::test]
async fn connect_unary_error_code_and_message() {
    let address = spawn_connect_server().await;
    let config = connect_config(&address, None);

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "boom" }),
    )
    .await
    .expect("connect unary error call");

    let error = resp.error.expect("expected a Connect error");
    assert_eq!(error.code, 5, "not_found = 5");
    assert!(
        error.message.contains("greeting not found"),
        "message: {}",
        error.message
    );
}

#[tokio::test]
async fn connect_unary_error_details() {
    let address = spawn_connect_server().await;
    let config = connect_config(&address, None);

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "boom-details" }),
    )
    .await
    .expect("connect unary error-details call");

    let error = resp.error.expect("expected a Connect error");
    assert_eq!(error.code, 3, "invalid_argument = 3");

    // For HTTP transports the Connect `details` array is carried as raw JSON-array
    // bytes; assert it round-trips with the type + value intact.
    let details: Value =
        serde_json::from_slice(&error.details).expect("details should be a JSON array");
    assert_eq!(details[0]["type"], json!("google.rpc.ErrorInfo"));
    assert_eq!(details[0]["value"], json!(DETAIL_VALUE_B64));
}

#[tokio::test]
async fn connect_unary_leading_metadata_header() {
    let address = spawn_connect_server().await;
    let config = connect_config(&address, None);

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "World" }),
    )
    .await
    .expect("connect unary call");

    let response = resp.messages.first().cloned().unwrap_or(json!({}));
    let header = engine()
        .evaluate(
            "@header(\"x-custom-header\") == \"custom-value\"",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @header");
    assert_eq!(header, AssertionResult::Pass, "headers: {:?}", resp.headers);
}

#[tokio::test]
async fn connect_server_streaming_multiple() {
    let address = spawn_connect_server().await;
    let desc = descriptor_file();
    let config = connect_config(&address, Some(&desc.path().to_string_lossy()));

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "ServerStream",
        json!({ "prefix": "item", "count": 3 }),
    )
    .await
    .expect("connect server-streaming call");

    assert!(resp.error.is_none(), "unexpected error: {:?}", resp.error);
    assert_eq!(resp.messages.len(), 3, "messages: {:?}", resp.messages);
    assert_eq!(resp.messages[0]["message"], json!("item #0"));
    assert_eq!(resp.messages[2]["message"], json!("item #2"));

    // The EndStreamMessage `metadata` surfaces as trailers.
    let response = resp.messages.first().cloned().unwrap_or(json!({}));
    let trailer = engine()
        .evaluate(
            "@trailer(\"x-stream-trailer\") == \"trailer-value\"",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @trailer");
    assert_eq!(
        trailer,
        AssertionResult::Pass,
        "trailers: {:?}",
        resp.trailers
    );
}

#[tokio::test]
async fn connect_streaming_end_stream_error_and_trailers() {
    let address = spawn_connect_server().await;
    let desc = descriptor_file();
    let config = connect_config(&address, Some(&desc.path().to_string_lossy()));

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "ServerStream",
        json!({ "prefix": "err", "count": 0 }),
    )
    .await
    .expect("connect streaming error call");

    // Data frames delivered before the failing end-of-stream frame are still seen.
    assert_eq!(resp.messages.len(), 2, "messages: {:?}", resp.messages);

    let error = resp.error.expect("expected an end-stream error");
    assert_eq!(error.code, 8, "resource_exhausted = 8");
    assert!(
        error.message.contains("stream blew up"),
        "message: {}",
        error.message
    );

    // Streaming errors also carry `details` (raw JSON-array bytes).
    let details: Value =
        serde_json::from_slice(&error.details).expect("details should be a JSON array");
    assert_eq!(details[0]["type"], json!("google.rpc.RetryInfo"));

    // Trailers from the EndStreamMessage `metadata` drive `@trailer(...)`.
    let response = resp.messages.first().cloned().unwrap_or(json!({}));
    let present = engine()
        .evaluate(
            "@trailer(\"x-stream-trailer\")",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @trailer present");
    assert_eq!(
        present,
        AssertionResult::Pass,
        "trailers: {:?}",
        resp.trailers
    );

    let value = engine()
        .evaluate(
            "@trailer(\"x-stream-trailer\") == \"trailer-value\"",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @trailer value");
    assert_eq!(
        value,
        AssertionResult::Pass,
        "trailers: {:?}",
        resp.trailers
    );
}

#[tokio::test]
async fn connect_streaming_leading_metadata_header() {
    let address = spawn_connect_server().await;
    let desc = descriptor_file();
    let config = connect_config(&address, Some(&desc.path().to_string_lossy()));

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "ServerStream",
        json!({ "prefix": "item", "count": 1 }),
    )
    .await
    .expect("connect server-streaming call");

    let response = resp.messages.first().cloned().unwrap_or(json!({}));
    let header = engine()
        .evaluate(
            "@header(\"x-custom-header\") == \"custom-value\"",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @header");
    assert_eq!(header, AssertionResult::Pass, "headers: {:?}", resp.headers);
}
