#![cfg(feature = "test-servers")]

use std::sync::Arc;

use grpctestify::assert::engine::{AssertionEngine, AssertionResult};
use grpctestify::grpc::client::{CompressionMode, GrpcClientConfig, ProtoConfig, WireProtocol};
use grpctestify::grpc::web::execute_web;
use grpctestify::plugins::PluginManager;

use prost::bytes::Bytes;
use serde_json::json;
use tempfile::NamedTempFile;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tonic::codec::CompressionEncoding;
use tonic::transport::Server;
use tonic::transport::server::TcpIncoming;
use tonic::{Code, Request, Response, Status, Streaming};
use tonic_web::GrpcWebLayer;

mod echo_proto {
    tonic::include_proto!("echo");
}

use echo_proto::{
    BidiResponse, EchoResponse, HelloResponse, RepeatResponse, StreamResponse,
    echo_service_server::{EchoService, EchoServiceServer},
};

// FileDescriptorSet for the reference test services (echo/auth/validation),
// generated by build.rs under the `test-servers` feature. The grpc-web transport
// needs a descriptor to marshal JSON <-> protobuf.
const TEST_SERVERS_DESCRIPTOR: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/test_servers_descriptor.bin"));

// A recognizable `grpc-status-details-bin` payload. Shaped like a `google.rpc.Status`
// (field 1 = code varint, field 2 = message string) so the bytes are a plausible
// status detail; the transport carries them verbatim and we assert an exact
// round-trip to prove tonic-web forwards the details trailer (recent-work GAP 1).
const STATUS_DETAILS: &[u8] = &[0x08, 0x05, 0x12, 0x04, b'b', b'o', b'o', b'm'];

struct WebEcho;

#[tonic::async_trait]
impl EchoService for WebEcho {
    async fn say_hello(
        &self,
        request: Request<echo_proto::HelloRequest>,
    ) -> Result<Response<HelloResponse>, Status> {
        let message = request.into_inner().message;
        if message == "boom" {
            return Err(Status::with_details(
                Code::NotFound,
                "greeting not found",
                Bytes::from_static(STATUS_DETAILS),
            ));
        }
        let mut response = Response::new(HelloResponse {
            message: format!("Hello, {}!", message),
        });
        // Leading metadata — surfaces as an HTTP response header over grpc-web.
        response
            .metadata_mut()
            .insert("x-custom-header", "custom-value".parse().unwrap());
        Ok(response)
    }

    async fn echo(
        &self,
        request: Request<echo_proto::EchoRequest>,
    ) -> Result<Response<EchoResponse>, Status> {
        let inner = request.into_inner();
        Ok(Response::new(EchoResponse {
            text: inner.text,
            count: inner.count,
        }))
    }

    async fn repeat(
        &self,
        _request: Request<Streaming<echo_proto::RepeatRequest>>,
    ) -> Result<Response<RepeatResponse>, Status> {
        Err(Status::unimplemented(
            "client streaming not used in these tests",
        ))
    }

    type ServerStreamStream = ReceiverStream<Result<StreamResponse, Status>>;

    async fn server_stream(
        &self,
        request: Request<echo_proto::StreamRequest>,
    ) -> Result<Response<Self::ServerStreamStream>, Status> {
        let inner = request.into_inner();
        let (tx, rx) = mpsc::channel(8);
        tokio::spawn(async move {
            for i in 0..inner.count {
                let response = StreamResponse {
                    index: i,
                    message: format!("{} #{}", inner.prefix, i),
                };
                if tx.send(Ok(response)).await.is_err() {
                    break;
                }
            }
        });
        Ok(Response::new(ReceiverStream::new(rx)))
    }

    type BidiStreamStream = ReceiverStream<Result<BidiResponse, Status>>;

    async fn bidi_stream(
        &self,
        _request: Request<Streaming<echo_proto::BidiRequest>>,
    ) -> Result<Response<Self::BidiStreamStream>, Status> {
        Err(Status::unimplemented(
            "bidi streaming not used in these tests",
        ))
    }
}

/// Spawn the echo service behind tonic-web's `GrpcWebLayer` on an ephemeral port,
/// returning its `http://host:port` base address. `accept_http1(true)` is required
/// because the grpc-web transport speaks HTTP/1.1.
async fn spawn_web_server() -> String {
    let incoming = TcpIncoming::bind("127.0.0.1:0".parse().unwrap()).expect("bind ephemeral port");
    let addr = incoming.local_addr().expect("local addr");

    tokio::spawn(async move {
        Server::builder()
            .accept_http1(true)
            .layer(GrpcWebLayer::new())
            .add_service(
                EchoServiceServer::new(WebEcho)
                    .accept_compressed(CompressionEncoding::Gzip)
                    .send_compressed(CompressionEncoding::Gzip),
            )
            .serve_with_incoming(incoming)
            .await
            .expect("server run");
    });

    format!("http://{}", addr)
}

/// Descriptor file kept alive for the duration of a test (drop = delete).
fn descriptor_file() -> NamedTempFile {
    let file = NamedTempFile::new().expect("temp descriptor");
    std::fs::write(file.path(), TEST_SERVERS_DESCRIPTOR).expect("write descriptor");
    file
}

fn web_config(
    address: &str,
    descriptor_path: &str,
    compression: CompressionMode,
) -> GrpcClientConfig {
    GrpcClientConfig {
        address: address.to_string(),
        timeout_seconds: 5,
        tls_config: None,
        proto_config: Some(ProtoConfig {
            files: vec![],
            import_paths: vec![],
            descriptor: Some(descriptor_path.to_string()),
        }),
        metadata: None,
        target_service: None,
        compression,
        connection_id: 0,
        protocol: WireProtocol::GrpcWeb,
        version: "test".to_string(),
    }
}

#[tokio::test]
async fn grpc_web_unary_success() {
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::None,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "World" }),
    )
    .await
    .expect("grpc-web unary call");

    assert!(resp.error.is_none(), "unexpected error: {:?}", resp.error);
    assert_eq!(resp.messages.len(), 1, "messages: {:?}", resp.messages);
    assert_eq!(resp.messages[0]["message"], json!("Hello, World!"));
}

// BUG: the grpc-web transport ignores a "Trailers-Only" response. tonic-web
// answers an immediate RPC error with HTTP 200, an EMPTY body, and
// grpc-status/grpc-message/grpc-status-details-bin in the HTTP *headers* (no
// in-body trailer frame). `grpc_web_binary`/`grpc_web_json` in src/grpc/web.rs
// parse status only from the body trailer frame and never inspect response
// headers, so the error is silently dropped (resp.error == None, trailers == {}).
// See report; fix belongs in src/grpc/web.rs, not here.
#[tokio::test]
async fn grpc_web_error_status_code_and_message() {
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::None,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "boom" }),
    )
    .await
    .expect("grpc-web error call");

    let error = resp.error.expect("expected a gRPC error");
    assert_eq!(error.code, 5, "NotFound = 5");
    assert!(
        error.message.contains("greeting not found"),
        "message: {}",
        error.message
    );
}

// BUG (same root cause as above): tonic-web DOES forward
// `grpc-status-details-bin` (confirmed: it is present in the response headers),
// but because the whole Trailers-Only response is header-only with an empty body,
// web.rs never reads it. GAP 1 details handling is therefore unreachable for the
// immediate-error case over grpc-web.
#[tokio::test]
async fn grpc_web_error_details_bin_forwarded() {
    // Validates GAP 1: tonic-web forwards `grpc-status-details-bin` and the
    // transport decodes it into `GrpcError::details` verbatim.
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::None,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "boom" }),
    )
    .await
    .expect("grpc-web error call");

    let error = resp.error.expect("expected a gRPC error");
    assert_eq!(
        error.details, STATUS_DETAILS,
        "grpc-status-details-bin should round-trip over grpc-web"
    );
}

// BUG: even on the success path (where an in-body trailer frame IS present),
// `@trailer(...)` sees nothing over grpc-web. `parse_grpc_web_trailers` in
// src/grpc/web.rs:1074 splits each trailer line on `": "` (colon + SPACE), but
// tonic-web (and the gRPC-Web wire format) emit `grpc-status:0` with NO space, so
// NO trailer is ever parsed from the frame (resp.trailers == {}). This also means
// an in-body `grpc-status:<non-zero>` error trailer would be missed. The parser
// should split on the first ':' and trim the value. Fix belongs in src/grpc/web.rs.
#[tokio::test]
async fn grpc_web_trailers_via_assert_engine() {
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::None,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "World" }),
    )
    .await
    .expect("grpc-web unary call");

    // grpc-status is a genuine server-set trailer carried in the grpc-web trailer
    // frame; drive it through the real `@trailer(...)` operator.
    let engine = AssertionEngine::with_registry(Arc::new(PluginManager::new()));
    let response = resp.messages.first().cloned().unwrap_or(json!({}));

    let present = engine
        .evaluate(
            "@trailer(\"grpc-status\")",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @trailer");
    assert_eq!(
        present,
        AssertionResult::Pass,
        "trailers: {:?}",
        resp.trailers
    );

    let value = engine
        .evaluate(
            "@trailer(\"grpc-status\") == \"0\"",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @trailer value");
    assert_eq!(
        value,
        AssertionResult::Pass,
        "trailers: {:?}",
        resp.trailers
    );

    // A missing trailer must fail the operator.
    let missing = engine
        .evaluate(
            "@trailer(\"x-not-present\")",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate missing @trailer");
    assert!(matches!(missing, AssertionResult::Fail { .. }));
}

// BUG (same root cause): the error's grpc-status arrives as an HTTP header on a
// Trailers-Only response, so `resp.trailers` is empty and `@trailer("grpc-status")`
// cannot see the failing status over grpc-web.
#[tokio::test]
async fn grpc_web_error_trailers() {
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::None,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "boom" }),
    )
    .await
    .expect("grpc-web error call");

    assert_eq!(
        resp.trailers.get("grpc-status").map(String::as_str),
        Some("5"),
        "trailers: {:?}",
        resp.trailers
    );
}

#[tokio::test]
async fn grpc_web_leading_metadata_header() {
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::None,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "World" }),
    )
    .await
    .expect("grpc-web unary call");

    // Leading metadata set by the server surfaces as an HTTP header over grpc-web.
    let engine = AssertionEngine::with_registry(Arc::new(PluginManager::new()));
    let response = resp.messages.first().cloned().unwrap_or(json!({}));
    let header = engine
        .evaluate(
            "@header(\"x-custom-header\") == \"custom-value\"",
            &response,
            Some(&resp.headers),
            Some(&resp.trailers),
        )
        .expect("evaluate @header");
    assert_eq!(header, AssertionResult::Pass, "headers: {:?}", resp.headers);
}

#[tokio::test]
async fn grpc_web_server_streaming() {
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::None,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "ServerStream",
        json!({ "prefix": "item", "count": 3 }),
    )
    .await
    .expect("grpc-web server streaming call");

    assert!(resp.error.is_none(), "unexpected error: {:?}", resp.error);
    assert_eq!(resp.messages.len(), 3, "messages: {:?}", resp.messages);
    assert_eq!(resp.messages[0]["message"], json!("item #0"));
    assert_eq!(resp.messages[2]["message"], json!("item #2"));
}

#[tokio::test]
async fn grpc_web_gzip_request_roundtrip() {
    // Drives a gzip-compressed request frame (client flag 0x01 + grpc-encoding:
    // gzip) against a server configured to accept gzip, validating gzip framing.
    let address = spawn_web_server().await;
    let desc = descriptor_file();
    let config = web_config(
        &address,
        &desc.path().to_string_lossy(),
        CompressionMode::Gzip,
    );

    let resp = execute_web(
        &config,
        "echo.EchoService",
        "SayHello",
        json!({ "message": "Gzip" }),
    )
    .await
    .expect("grpc-web gzip call");

    assert!(resp.error.is_none(), "unexpected error: {:?}", resp.error);
    assert_eq!(resp.messages.len(), 1, "messages: {:?}", resp.messages);
    assert_eq!(resp.messages[0]["message"], json!("Hello, Gzip!"));
}
