[package]
name = "apif-report"
version = "0.2.3"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
description = "Reporters for .apif/.gctf test results"

[dependencies]
apif-state = { path = "../apif-state", version = "0.1.2" }
anyhow = { workspace = true }
apif-cfg-runtime = { path = "../apif-cfg-runtime", version = "0.1.0" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
tracing = { workspace = true }
console = "0.16"
minijinja = { workspace = true }

[dev-dependencies]
tempfile = "3.27"

[lints]
workspace = true
